### ISSUE TITLE
can't open books either from cl  or from GUI 

### ISSUE THREAD

**Issue by bazidev** [ojuba-org/thawab-lite#2]
- Ubuntu 16.04.4 LTS
- python2 
i am not able to open a bok file 
i tried to pass the book name as a cl parametre 
`python thawab-lite.py kitab.bok`
i got this 

> Traceback (most recent call last):
  File "thawab-lite.py", line 224, in <module>
    MyApp(f)
  File "thawab-lite.py", line 127, in __init__
    self.open(filename)
  File "thawab-lite.py", line 160, in open
    cols = get_table_col(filename, 'Main')
  File "thawab-lite.py", line 67, in get_table_col
    out = subprocess.check_output(["mdb-schema", "-T", table_name, filename, 'mysql'])
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

i thought this may be because of the arabic name of the book, i changed the name i still have the same error 

then i tried to open the book from the GUI 
i got this 

> ERROR:__main__:ERROR: OSError(2, 'No such file or directory')

**Comment by muayyad-alsadi** [comment]
> out = subprocess.check_output(["mdb-schema", "-T", table_name, filename, 'mysql'])
> OSError: [Errno 2] No such file or directory

You need to install `mdb-tools` as indicated in the README.md
